# Generated by Django 5.2.1 on 2025-06-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tittle',
            new_name='title',
        ),
    ]
