# Generated by Django 5.2.3 on 2025-07-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='Province',
        ),
    ]
