# Generated by Django 5.2.3 on 2025-07-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_state_customer_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='PostalCode',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Province',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='suburb',
        ),
    ]
